apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openpanel

resources:
  - ../../../base/openpanel

images:
  - name: ghcr.io/rubenlopsol/devops-lab-app
    newTag: main-558a42f

patches:
  - path: configmap-patch.yaml
