apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/argocd/applications
  - ../../../base/argocd/projects

helmCharts:
  - name: argo-cd
    repo: https://argoproj.github.io/argo-helm
    version: "7.7.0"
    releaseName: argocd
    namespace: argocd
    valuesFile: ../../../base/argocd/install/values.yaml
    additionalValuesFiles:
      - values.yaml
    includeCRDs: true

labels:
  - pairs:
      environment: dev
      project: openpanel
    includeSelectors: false
